### ISSUE TITLE
Show random recipe 

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#1]
## Value Proposition

**As a user**
**I need to** be shown a random recipe
**to be able to** get an idea for a healthy meal

## Description 
![reworkedIssue1](https://user-images.githubusercontent.com/98756387/159668558-571ddd4e-8859-4a3a-99ab-86a1a35f4fd4.png)

## Acceptance Criteria

- [x] a card is displayed with a random meal
- [x] below the card is a button get a new random recipe

## Tasks 

- [x] create a branch `random-meal`
- [x]  create a json with recipe data
- [x]  create a component button 
- [x]  create button story
- [x]  create button spec
- [x]  create a component card
- [x]  create card story
- [x]  create card spec
- [x]  write a function for the button click event to get data from db and show  new card 
- [x] Test on mobile device / different Browser
