### ISSUE TITLE
Back-End fetch

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#16]
## Value Proposition 

**As a developer**
**I need to**  save data 
**to be able to** send request to the api server-side and work with the api response for every user individually

## Description 
<img src="https://user-images.githubusercontent.com/98756387/161512100-81fe73cc-2ed6-4123-89ce-cc4fcfefdafa.png" width="1000" height="1000" />

## Acceptance Criteria

- [x] doesn't send request to the api from the front-end
- [x] gets data from back-end
- [x] doesn't need local Storage anymore  

## Task

- [x] install vercel
- [x] install swr 
- [x] install mongoose
- [x] setup mongoDB atlas 
- [x] write fetch to backend api 
- [x] rewrite fetch to spoonacular api
