### ISSUE TITLE
Toggle form and result

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#17]
## Value Proposition 

**As a use**
**I need to**  see my result without the form still persisting
**to be able to** get a better look at the recipe

## Description 
<img src="https://user-images.githubusercontent.com/98756387/161512100-81fe73cc-2ed6-4123-89ce-cc4fcfefdafa.png" width="1000" height="1000" />

## Acceptance Criteria

- [x] after submitting the form disappears 
- [x] just the recipe is shown 
- [x] if i delete or save the recipe, the recipe disappears and the form reappears

## Task

- [x] implement conditional rendering, so if a result is given the result is rendered.
- [x] if recipe is saved or deleted it is removed from results and the form is rerendered
