### ISSUE TITLE
Save data to mongoDB and get it back 

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#19]
## Value Proposition 

**As a user**
**I need to**  save my recipes
**to be able to** have access to  the recipe information after a refresh or restart

## Description 
<img src="https://user-images.githubusercontent.com/98756387/161512100-81fe73cc-2ed6-4123-89ce-cc4fcfefdafa.png" width="1000" height="1000" />

## Acceptance Criteria

- [x] save recipe via save button on recipe
- [x] after refresh recipes stay in list
- [x] delete button delete recipes from list and backend

## Task

- [x] set up mongoDB 
- [x] set up Mongoose
- [x] create save button in Recipe component 
- [x] write POST request in api
- [x] write GET request in api
- [x] write save function with GET gequest for save button
- [x] update spec
