### ISSUE TITLE
Use API

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#2]
## Value Proposition 

**As a user**
**I need to** be shown more random meal recipes
**to be able to** get more inspirational healthy food ideas

## Description 

<img src="https://user-images.githubusercontent.com/98756387/159669156-78403f92-e7c3-402a-a3af-0c383c224b40.png" width="400" height="800" />

## Acceptance Criteria

- [x] after button is clicked a random recipe appears from  api spoonacular
- [x] recipe is displayed in card with  picture, data and link
- [x] after clicking button below the card new data is fetched and new recipe is displayed

## Tasks

- [x] create new branch `fetch`
- [x] create list of random ingredients to give to the fetch 
- [x] create a fetch function and implement to button 
- [x]  rework card component to display fetched data
- [x] update styles if necessary
- [x]  Test on mobile device / different Browser
