### ISSUE TITLE
smaller Cards with toggle function on favorites

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#22]
## Value Proposition 

**As a user** 
**I need to**  have a better overview over my saved recipes
**to be able to** navigate faster

## Description 
<img src="https://user-images.githubusercontent.com/98756387/162743845-08059cfa-4ec5-4678-98cb-35ee0ea51820.png" width="1000" height="1000" />

## Acceptance Criteria

- [ ] Recipes in favorites appear in smaller card
- [ ] when user clicks on card in extendes
- [ ] when user clicks again, it folds back to the smaller version

## Task

- [ ] create small Recipe component 
- [ ] write a onClick toggle function 
- [ ] write test for small card
- [ ] write storie for small card
- [ ] rewrite spec for recipe list
- [ ] rewrite spec for recipe component
- [ ] rework styling
