### ISSUE TITLE
Login function

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#26]
## Value Proposition 

**As a user**
**I need to** login to my own profile
**to be able to** have access to individually saved recipes

## Description 
<img src="https://user-images.githubusercontent.com/98756387/163575644-e93e35f8-ad72-4cb3-bb9c-2d8bca730974.png" width="1000" height="1000" />

## Acceptance Criteria

- [x] login in to a premade profile via login form 
- [x] login via github 
- [x] save searched recipes to profile 
- [x] see saved recipes in favortes 
- [x] every profile has different favorites
- [x] delete recipes individually for every profile 

## Task

- [x] and User schema 
- [x] Add profile page
- [x] Add login page with login form 
- [x] Add profile endpoint 
- [x] Add login endpoint 
- [x] Add login function front end
- [x] Add oauth GitHub 
- [x] update Save function frontend
- [x] update save backend
- [x] update delete frontend 
- [x] update delete backend
