### ISSUE TITLE
Stay Logged in with local storage

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#27]
## Value Proposition 

**As a user**
**I need to** stay logged in 
**to be able to** refresh the browser without being logged out

## Description 
<img src="https://user-images.githubusercontent.com/98756387/163575644-e93e35f8-ad72-4cb3-bb9c-2d8bca730974.png" width="1000" height="1000" />

## Acceptance Criteria

- [x] after logging in and refreshing the browser user is still logged in

 
## Task

- [x] implement a function to save the access token to local storage 
- [x] implement a function to load the access token from local storage
