### ISSUE TITLE
Toastify

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#28]
## Value Proposition 

**As a user**
**I need to** be better informed about my actions
**to be able to** understand what happens when I interact with the interface

## Description 
<img src="https://user-images.githubusercontent.com/98756387/163575644-e93e35f8-ad72-4cb3-bb9c-2d8bca730974.png" width="1000" height="1000" />

## Acceptance Criteria

- [x] all alarms are removed
- [x] all alarms are replaced by adequate toasts

 
## Task

- [x] install react-toastify
- [x] find adequate replacement for the alarms
- [x] replace alarms withe toast
