### ISSUE TITLE
Create Form

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#3]
## Value Proposition 

**As a user**
**I need to** submit my meal ingredients I want to use
**to be able to** get a fitting recipe idea 

## Description
<img src="https://user-images.githubusercontent.com/98756387/159943962-4b27c213-df90-43f5-b0fa-4c39fcb94875.svg" width="400" height="1000" />

## Acceptance Criteria

- [x] user can put up to 5 ingredients into the form
- [x] user has to put in at least two ingredients
- [x] user can click the submit button and a recipe card is displayed below 
- [x] #11
- [x] after new submit a new card is rendered
- [x] The form is always visible
- [x] if the request fails due to not fitting ingredients there will be a display that the search failed(this will be in a later issue) 

## Tasks

- [x] create a form with 5 input fields and a submit button
- [x] storybook for form component 
- [x] #12
- [x] update fetch, so a random recipe is fetch with the right ingredients 
- [x] create a card-list
- [x] update card component so it show the correct data
- [x] update card component "missing ingredients"

**Comment by PReichetanz** [comment]
Questions:
- What happens if no recipe fits the ingredients submitted? What kind of card is displayed?
- Is the form always visible?

**Comment by tRomanowski** [comment]
Thanks Paul for your feedback. Sorry I didn't see it earlier. 
Yes the form will always be visible and the case where no recipe is received, because no ingredients fitted will be an issue for a later user story. 
I will update the user story with your thoughts. 👍
