### ISSUE TITLE
Save Recipe

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#4]
## Value Proposition 

**As a user**
**I need to** get access to my previous searches after refreshing or closing the tap
**to be able to** look up older recipes or the same recipe after accidentally closing the tap

## Description  
<img src="https://user-images.githubusercontent.com/98756387/159943962-4b27c213-df90-43f5-b0fa-4c39fcb94875.svg" width="400" height="1000" />

## Acceptance Criteria

- [x] after refreshing, the recipes are still rendered

## Tasks

- [x] save recipe data to local storage
- [x] get recipe data from local storage when loading the app
