### ISSUE TITLE
Delete Card

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#5]
## Value Proposition 

**As a user**
**I need to** delete old recipes or recipes I don’t want
**to be able to** see only the recipes that are currently relevant to me

## Description 
<img src="https://user-images.githubusercontent.com/98756387/159956776-d7dad2c5-dcc1-4a7e-9065-b29cc04dff21.png" width="400" height="1000" />

## Acceptance Criteria

- [x] after clicking the delete button in the recipe card, the recipe is deleted for the recipe list and from the local storage

## Task

- [x] implement a delete button in the card component
- [x] create an on click event for the button, that deletes the recipe
- [x] update storybook 
- [x] update card test
