### ISSUE TITLE
Add checkboxes for type of meal to the form

### ISSUE THREAD

**Issue by tRomanowski** [tRomanowski/capstone-project#6]
## Value Proposition

**As a user**
**I need to** decide whether I want breakfast, lunch or dinner
**to be able to** find a fitting recipe

## Description 
<img src="https://user-images.githubusercontent.com/98756387/160344120-d8fe3c06-fc4f-4f72-93d2-57bbbdd40cc4.png" width="400" height="1200" /> 

## Acceptance Criteria

- [ ] in the form i can choose whether I want breakfast, lunch or dinner
- [ ] only on option can be chosen
- [ ] after submitting the form the result fits the chosen meal type and is displayed

## Task

- [ ] extend the form with radio button inputs for breakfast, lunch and dinner 
- [ ] change the fetch to search for fitting entries

**Comment by tRomanowski** [comment]
does not work with the api. Ui/Ux changed in other user stories
